### PR TITLE
Added indent-spaces to tidyconfig.txt

### PR DESCRIPTION
**Pull request by sahel-sh**
I ran:
```console
tidy -config ./tidyconfig.txt -o ~/tidy.html ./index.html
vimdiff ~/tidy.html ./index.html
cp ~/tidy.html ./index.html
```

***
<a href="https://pr-preview.s3.amazonaws.com/sahel-sh/payment-handler/pull/348.html" title="Last updated on Oct 17, 2019, 5:43 PM UTC (ad2876b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/348/d617c77...sahel-sh:ad2876b.html" title="Last updated on Oct 17, 2019, 5:43 PM UTC (ad2876b)">Diff</a>

### CODE REVIEW

**Review by ianbjacobs — APPROVED** [review]
Thanks, Sahel. Assuming that's all that's changed, ok by me.

**Comment by rsolomakhin** [comment]
It's surprising that `indent: yes` in the tidyconfig.txt file seems to have no effect, because the pull request is removing all indents. What version of tidy was used?

**Comment by ianbjacobs** [comment]
@rsolomakhin , thanks for doing more work to check the PR than I did. For the record, I use Tidy 5.6.0.

**Comment by sahel-sh** [comment]
HTML Tidy for Linux version 5.6.0 is the version that I used

**Comment by sahel-sh** [comment]
The new default for indent-spaces was zero, I added it to the config file.
Please take another look.

**Review by rsolomakhin — APPROVED** [review]
Thank you for looking into this!

**Pull request merged**
