### PR TITLE
Bring back shipping and contact information.

### PR DESCRIPTION
**Pull request by rsolomakhin**
This reverts commit 6d44221837ece704467a7c7eed0b37de1987059e: "Remove support for address, contact info from PR API (align with pull request 955) (#389)."

***
<a href="https://pr-preview.s3.amazonaws.com/rsolomakhin/payment-handler/pull/406.html" title="Last updated on Jan 11, 2023, 5:20 PM UTC (2099946)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/406/3a6c1e8...rsolomakhin:2099946.html" title="Last updated on Jan 11, 2023, 5:20 PM UTC (2099946)">Diff</a>

### CODE REVIEW

**Comment by rsolomakhin** [comment]
As addresses and contact-info are coming back to PaymentRequest API, we would like to keep address/contact-info support in Payment Handler API, too. @stephenmcgruer & @ianbjacobs PTAL.

**Comment by ianbjacobs** [comment]
Hi @rsolomakhin,

Are there any changes to the text other than restoring what was once there?

Also, I'd like to request the addition of an informative note acknowledging that we will be looking at privacy implications of restoring these features. See my suggested text in PR API:
  https://github.com/w3c/payment-request/pull/996#issuecomment-1258634717

Thank you!

**Comment by rsolomakhin** [comment]
Hi @ianbjacobs!

Should this pull request be discussed in a W3C meeting before merging?

> Are there any changes to the text other than restoring what was once there?

I also cleaned up a couple of ReSpec warnings. That should be negligible. This is 99.9% restoring what was once there.

> Also, I'd like to request the addition of an informative note acknowledging that we will be looking at privacy implications of restoring these features. See my suggested text in PR API:

I've placed your suggested text in the "Security and Privacy Considerations" section.

**Comment by rsolomakhin** [comment]
Let's **not** bring back `requestBillingAddress` because that was never implemented in Payment Handlers and we don't have concrete plans to implement that in Payment Handlers.

**Comment by ianbjacobs** [comment]
Thanks for this, @rsolomakhin. Would you be available for a brief summary at the end of the 19 January call?

**Review by ianbjacobs — APPROVED** [review]

**Comment by rsolomakhin** [comment]
> Would you be available for a brief summary at the end of the 19 January call?

Yes, I will attend and summarize.

Should this be merged after the 19 January call, or can it be merged now, in your opinion?

**Comment by ianbjacobs** [comment]
I'm fine personally if you want to merge now and then discuss. I would like to be sure in the discussion that we understand the motivation for the restoration and discuss a process for addressing the privacy concerns previously raised. Thanks again and talk to you on the 19th.

**Comment by rsolomakhin** [comment]
@stephenmcgruer - Are you also OK with the plan in the https://github.com/w3c/payment-handler/pull/406#issuecomment-1379325933?

**Review by stephenmcgruer — APPROVED** [review]
I did not review the PR in-depth, trusting that it is as described in the above conversation, but the plan SGTM. Thanks Rouslan!

**Pull request merged**
