### PR TITLE
BREAKING CHANGE: Change topLevelOrigin to topOrigin

### LINKED ISSUE #259: topLevelOrigin is a weird name
I don't think we've ever used "top level" in a public API before.

We do have `window.top` though. Maybe `topOrigin` is a bit better.

Is there any way of referring to this by its actual function? For example its description says "This attribute is a string that indicates the origin of the top level payee web page." Could `payeeOrigin` work? (If not, that description is probably not great.)

### PR DESCRIPTION
**Pull request by ianbjacobs**
closes #259 

The following tasks have been completed:

 * [ ] [web platform tests](https://github.com/w3c/web-platform-tests/pull/10872)
 * [ ] MDN Docs added (link)

Implementation commitment:

 * [ ] Safari (link to issue)
 * [x] Chrome (link to issue)
 * [ ] Firefox (link to issue)
 * [ ] Edge (public signal)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/pull/301.html" title="Last updated on May 9, 2018, 2:58 AM GMT (abceef7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/301/2185538...abceef7.html" title="Last updated on May 9, 2018, 2:58 AM GMT (abceef7)">Diff</a>

### CODE REVIEW

**Review by romandev — APPROVED** [review]
lgtm

I made a patch in Chromium as well.
https://chromium-review.googlesource.com/c/chromium/src/+/1045705

**Comment by marcoscaceres** [comment]
🎵🎶don’t forget to do the checklist at the top of the pull request. If you love a speciation, it should have tests! 🎸 

All together now! 🎹 

(That’s quite a catchy tune)

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres, 

Whoops; sorry about that. Let me see if we have tests already (to be modified).

**Comment by ianbjacobs** [comment]
@marcoscaceres and @romandev,
Here is a pull request to update the name in the existing tests:
 https://github.com/w3c/web-platform-tests/pull/10873

I did not write a new test, however.

**Comment by marcoscaceres** [comment]
Thanks! I don’t think new tests are needed, so we should be good.

**Comment by marcoscaceres** [comment]
Added link to WPT.

**Comment by marcoscaceres** [comment]
Just noting for future reference, when we rename IDL, that's generally labelled a "BREAKING CHANGE" (I know, all caps... but not as scary as it seems, specially early on!) - but it's important to note that we made a change that will impact real code (either browser or user-land), and definitely not "editorial".

**Pull request merged**
