### PR TITLE
Add [Exposed] to PaymentInstruments interface.

### LINKED ISSUE #215: Add [Exposed] to all interfaces
Needed for https://github.com/heycam/webidl/issues/365.

### PR DESCRIPTION
**Pull request by romandev**
This fixes #215.

### CODE REVIEW

**Comment by romandev** [comment]
Uploaded a test: https://github.com/w3c/web-platform-tests/pull/7371

**Comment by rsolomakhin** [comment]
Please update the interfaces file in tandem: https://github.com/w3c/web-platform-tests/blob/master/interfaces/payment-handler.idl

**Comment by rsolomakhin** [comment]
Thank you for updating the interfaces file. LGTM

**Review by rsolomakhin — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Merged test file into WPT.  

@ianbjacobs, when possible, please refrain from merging until tests are merged into WPT. That way, we don't end up with untested things in the spec. 

I've been using "needs tests" label in Payment Request. Might be good to do the same on Payment Handler side.

**Pull request merged**
