### PR TITLE
fix: PaymentInstruments.get not exceptional

### LINKED ISSUE #230: Trying to get a non-existing value is not exceptional
In `PaymentInstruments.get()` method

It states:
> Otherwise, reject p with a DOMException whose value is "NotFoundError".

This is not ideal, as trying to get something that might no longer be there is not "exceptional". It should just resolve with `undefined`.

### PR DESCRIPTION
**Pull request by marcoscaceres**
* closes #230

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/pull/231.html" title="Last updated on Nov 28, 2017, 2:31 AM GMT">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/55c501f...7eb932e.html" title="Last updated on Nov 28, 2017, 2:31 AM GMT">Diff</a>

### CODE REVIEW

**Review by romandev — APPROVED** [review]
lgtm

**Comment by marcoscaceres** [comment]
Thanks @romandev!

**Comment by marcoscaceres** [comment]
Want a tick from @rsolomakhin, confirming this is ok on the Chrome side.

**Review by rsolomakhin — APPROVED** [review]
Looks good! (Thank you for checking.)

**Comment by marcoscaceres** [comment]
@rsolomakhin, no biggy, but please be mindful of the don't merge labels 🙏 I only added them recently, so totally understandable if you missed them.

**Comment by rsolomakhin** [comment]
Whoa! Totally missed this. My bad!

**Comment by marcoscaceres** [comment]
I think @romandev prepared a test for this. @romandev, is that correct?

**Comment by romandev** [comment]
@marcoscaceres Sure, I'll update the tests soon (until tomorrow). Sorry for delay. (But if you are urgent, you can write a new PR?)

Thank you!

**Comment by marcoscaceres** [comment]
Not urgent at all :) let’s finish the discussions around clearing site data, in case we do end up changing the API.

**Pull request merged**
