### PR TITLE
Editorial: trim/relocate conformance

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/pull/226.html" title="Last updated on Nov 29, 2017, 3:51 AM GMT">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/5ae418c...18aa5d2.html" title="Last updated on Nov 29, 2017, 3:51 AM GMT">Diff</a>

### CODE REVIEW

**Review by adrianhopebailie — COMMENTED** [review]
This section was originally a direct copy of the same section in the PaymentRequest spec. It seems like you are trimming a lot here that is still in PR API. We should be consistent otherwise we are making meaningless subjective changes

**Comment by marcoscaceres** [comment]
> This section was originally a direct copy of the same section in the PaymentRequest spec. 

It not longer matches tho. I changed that one a long time ago.

> We should be consistent otherwise we are making meaningless subjective changes

I would never! 🤪🍸 I'll get this to match PR.

**Comment by marcoscaceres** [comment]
@adrianhopebailie, now they match 💃

**Review by adrianhopebailie — APPROVED** [review]
🥇

**Review by ianbjacobs — APPROVED** [review]

**Pull request merged**
