### PR TITLE
Shipping Address and Payer's Contact info Delegation

### LINKED ISSUE #337: Support delegating collection of shipping address and other user data to Payment Handler
Today if a merchant requests shipping address or payer's contact information, the data collection is always handled by the browser. At last week's WPWG FTF in Foster City, there was interest among payment providers to be able to provide this information. Supporting this delegation can lead to better user experience because the payment app may have more accurate information than the browser.

We should support delegation for all fields that are currently requested via `PaymentOptions`: https://w3c.github.io/payment-request/#dom-paymentoptions

### PR DESCRIPTION
**Pull request by sahel-sh**
closes #337

The following tasks have been completed:

 * [x] web platform tests (
[enable-shipping-contact-delegation](https://github.com/web-platform-tests/wpt/blob/master/payment-handler/supports-shipping-contact-delegation-manual.https.html),
[change-shipping-option](https://github.com/web-platform-tests/wpt/blob/master/payment-handler/change-shipping-option-manual.https.html),
[change-shipping-address](https://github.com/web-platform-tests/wpt/blob/master/payment-handler/change-shipping-address-manual.https.html))
 * [ ] MDN Docs added (link)

Implementation commitment:

 * [ ] Safari (link to issue)
 * [x] Chrome (crbug.com/984694)
 * [ ] Firefox (link to issue)
 * [ ] Edge (public signal)

***
<a href="https://pr-preview.s3.amazonaws.com/sahel-sh/payment-handler/pull/349.html" title="Last updated on Oct 17, 2019, 8:01 PM UTC (1a345b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-handler/349/4dabb06...sahel-sh:1a345b9.html" title="Last updated on Oct 17, 2019, 8:01 PM UTC (1a345b9)">Diff</a>

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]
Would you mind if merged https://github.com/w3c/payment-handler/pull/341 first? You might have to do a small rebase afterwards.

**Comment by sahel-sh** [comment]
Sure, I will rebase if needed.

**Comment by sahel-sh** [comment]
@adrianhopebailie I heard that you are interested in shipping and contact delegation progress.
FYI, please find the changes to PH API spec in this PR.

**Comment by adrianhopebailie** [comment]
cc @matdehaast

**Comment by marcoscaceres** [comment]
I'm a bit worried that this landed in the spec without much discussion. I'm a fan of the idea, but I'm wondering if we should note it in the spec as experimental?

**Comment by sahel-sh** [comment]
> I'm a bit worried that this landed in the spec without much discussion. I'm a fan of the idea, but I'm wondering if we should note it in the spec as experimental?

cc @danyao

**Pull request merged**
